// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBncO80QQz9vl6NzWZai3LX-4K7H73Yw-Q',
    appId: '1:568037284796:web:859daa4851cd9dbfa0e9b9',
    messagingSenderId: '568037284796',
    projectId: 'studentpg-aeb1e',
    authDomain: 'studentpg-aeb1e.firebaseapp.com',
    storageBucket: 'studentpg-aeb1e.appspot.com',
    measurementId: 'G-3C3EWQFF3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABsC2Rav5-JL_f55iKqBlKzy5_ufe_7fo',
    appId: '1:568037284796:android:33226421f0cdc981a0e9b9',
    messagingSenderId: '568037284796',
    projectId: 'studentpg-aeb1e',
    storageBucket: 'studentpg-aeb1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS0hNUVvy0hVPXkri5hBkutJJX7n1ZfWg',
    appId: '1:568037284796:ios:4fb2b517d589cadea0e9b9',
    messagingSenderId: '568037284796',
    projectId: 'studentpg-aeb1e',
    storageBucket: 'studentpg-aeb1e.appspot.com',
    iosClientId: '568037284796-0f7cgbca7mshfl3nbp58r6pl17r5f6am.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentpg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS0hNUVvy0hVPXkri5hBkutJJX7n1ZfWg',
    appId: '1:568037284796:ios:4fb2b517d589cadea0e9b9',
    messagingSenderId: '568037284796',
    projectId: 'studentpg-aeb1e',
    storageBucket: 'studentpg-aeb1e.appspot.com',
    iosClientId: '568037284796-0f7cgbca7mshfl3nbp58r6pl17r5f6am.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentpg',
  );
}
